# Generated by Django 4.2 on 2024-12-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bizzzapp", "0002_imagemodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seats",
            old_name="email",
            new_name="emails",
        ),
        migrations.RenameField(
            model_name="seats",
            old_name="message",
            new_name="messages",
        ),
        migrations.RenameField(
            model_name="seats",
            old_name="name",
            new_name="names",
        ),
        migrations.RemoveField(
            model_name="book",
            name="tickets",
        ),
    ]
