# Generated by Django 4.2 on 2024-12-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bizzzapp", "0003_rename_email_seats_emails_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seats",
            old_name="emails",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="seats",
            old_name="messages",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="seats",
            old_name="names",
            new_name="name",
        ),
    ]
