# Generated by Django 4.2 on 2024-12-13 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bizzzapp", "0004_rename_emails_seats_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="traveldate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
